apiVersion: v1
kind: Service
metadata:
  name: ml
spec:
  selector:
    app: ml-flask
  ports:
    - protocol: "TCP"
      port: 7000
      targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-flask
spec:
  selector:
    matchLabels:
      app: ml-flask
  replicas: 1
  template:
    metadata:
      labels:
        app: ml-flask
    spec:
      containers:
        - name: ml-flask
          image: docker.io/dksipl/ml-flask
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000